name: abarkhodro_application
description: "Ticket Application With Authorization"

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  get_it: ^8.0.3
  go_router: ^14.8.0
  freezed_annotation: ^2.4.4
  shamsi_date: ^1.0.4
  dio: ^5.8.0+1
  shared_preferences: ^2.5.1
  dartz: ^0.10.1
  shimmer_animation: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  retrofit_generator: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: IranSansMedium
      fonts:
        - asset: assets/fonts/IRANSansMedium.ttf
